import Dc.Mach.DcFuncSpec1
import Dc.Mach.DcFuncSpec2
import Dc.Mach.DcFuncSpec3
import Dc.Mach.DcFuncSpecB

/-!
# `dc_func`'s contract (generated by `scripts/dc/gen_dcf_spec.py`; do not edit)

`fnDone`: the characters of `9..126` whose arms are proved. `dc_func_spec_done`:
for each of them, and for every character outside the table, `dc_func` run
from its entry under `FnPre`/`FnRegs` continues as the caller's `FnK` for
`dcFunc 70 st c peek neg` (or reaches `dc_memfail`, `FnOom`).
-/

namespace Dc.Mach

open Vsa.MemRepr Vsa.Sim VsaIris VsaIris.Inst VsaIris.Sym VsaIris.MallocFast VsaIris.Interp
open LeanRV64DExecutable LeanRV64DExecutable.Functions Sail

/-- The characters of `9..126` whose `dc_func` arm is proved. -/
def fnDone : List Nat := [9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126]

/-- **`dc_func (c, peekc, negcmp)`** at `0x80000b9c` for `c` in `fnDone` or
outside the table. -/
theorem dc_func_spec_done {live S : Nat → Prop}
    {Q : String → (Nat → BitVec 64) → (Nat → BitVec 8) → Prop}
    (hlive : ∀ p ∈ dcText, live p.1) {t0 : String} {sp W : Nat} {M : Mem} {H : Heap}
    {F : List Blk} {L : List NumObj} {C : BcConsts} {G : DcG} {hs : List GV} {st : St}
    {c : Nat} {peek : Option Nat} {neg : Bool} {R : Nat → BitVec 64}
    (hc : c ∈ fnDone ∨ c < 9 ∨ 126 < c)
    (hp : FnPre S sp W M H F L C G hs st c peek) (hr : FnRegs R sp c peek neg)
    (ho : FnOom live S Q sp W M)
    (hk : FnK live S Q (leakAllow c) t0 st (dcFunc 70 st c peek neg) G hs sp W M R) :
    DWO live S Q (t0 ++ Dc.outStr st.out) 0x80000b9c#64 R M := by
  rcases hc with hc | hout
  · simp only [fnDone, List.mem_cons, List.not_mem_nil, or_false] at hc
    rcases hc with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
    · exact dcf_9 hlive hp hr ho hk
    · exact dcf_10 hlive hp hr ho hk
    · exact dcf_11 hlive hp hr ho hk
    · exact dcf_12 hlive hp hr ho hk
    · exact dcf_13 hlive hp hr ho hk
    · exact dcf_14 hlive hp hr ho hk
    · exact dcf_15 hlive hp hr ho hk
    · exact dcf_16 hlive hp hr ho hk
    · exact dcf_17 hlive hp hr ho hk
    · exact dcf_18 hlive hp hr ho hk
    · exact dcf_19 hlive hp hr ho hk
    · exact dcf_20 hlive hp hr ho hk
    · exact dcf_21 hlive hp hr ho hk
    · exact dcf_22 hlive hp hr ho hk
    · exact dcf_23 hlive hp hr ho hk
    · exact dcf_24 hlive hp hr ho hk
    · exact dcf_25 hlive hp hr ho hk
    · exact dcf_26 hlive hp hr ho hk
    · exact dcf_27 hlive hp hr ho hk
    · exact dcf_28 hlive hp hr ho hk
    · exact dcf_29 hlive hp hr ho hk
    · exact dcf_30 hlive hp hr ho hk
    · exact dcf_31 hlive hp hr ho hk
    · exact dcf_32 hlive hp hr ho hk
    · exact dcf_33 hlive hp hr ho hk
    · exact dcf_34 hlive hp hr ho hk
    · exact dcf_35 hlive hp hr ho hk
    · exact dcf_36 hlive hp hr ho hk
    · exact dcf_37 hlive hp hr ho hk
    · exact dcf_38 hlive hp hr ho hk
    · exact dcf_39 hlive hp hr ho hk
    · exact dcf_40 hlive hp hr ho hk
    · exact dcf_41 hlive hp hr ho hk
    · exact dcf_42 hlive hp hr ho hk
    · exact dcf_43 hlive hp hr ho hk
    · exact dcf_44 hlive hp hr ho hk
    · exact dcf_45 hlive hp hr ho hk
    · exact dcf_46 hlive hp hr ho hk
    · exact dcf_47 hlive hp hr ho hk
    · exact dcf_48 hlive hp hr ho hk
    · exact dcf_49 hlive hp hr ho hk
    · exact dcf_50 hlive hp hr ho hk
    · exact dcf_51 hlive hp hr ho hk
    · exact dcf_52 hlive hp hr ho hk
    · exact dcf_53 hlive hp hr ho hk
    · exact dcf_54 hlive hp hr ho hk
    · exact dcf_55 hlive hp hr ho hk
    · exact dcf_56 hlive hp hr ho hk
    · exact dcf_57 hlive hp hr ho hk
    · exact dcf_58 hlive hp hr ho hk
    · exact dcf_59 hlive hp hr ho hk
    · exact dcf_60 hlive hp hr ho hk
    · exact dcf_61 hlive hp hr ho hk
    · exact dcf_62 hlive hp hr ho hk
    · exact dcf_63 hlive hp hr ho hk
    · exact dcf_64 hlive hp hr ho hk
    · exact dcf_65 hlive hp hr ho hk
    · exact dcf_66 hlive hp hr ho hk
    · exact dcf_67 hlive hp hr ho hk
    · exact dcf_68 hlive hp hr ho hk
    · exact dcf_69 hlive hp hr ho hk
    · exact dcf_70 hlive hp hr ho hk
    · exact dcf_71 hlive hp hr ho hk
    · exact dcf_72 hlive hp hr ho hk
    · exact dcf_73 hlive hp hr ho hk
    · exact dcf_74 hlive hp hr ho hk
    · exact dcf_75 hlive hp hr ho hk
    · exact dcf_76 hlive hp hr ho hk
    · exact dcf_77 hlive hp hr ho hk
    · exact dcf_78 hlive hp hr ho hk
    · exact dcf_79 hlive hp hr ho hk
    · exact dcf_80 hlive hp hr ho hk
    · exact dcf_81 hlive hp hr ho hk
    · exact dcf_82 hlive hp hr ho hk
    · exact dcf_83 hlive hp hr ho hk
    · exact dcf_84 hlive hp hr ho hk
    · exact dcf_85 hlive hp hr ho hk
    · exact dcf_86 hlive hp hr ho hk
    · exact dcf_87 hlive hp hr ho hk
    · exact dcf_88 hlive hp hr ho hk
    · exact dcf_89 hlive hp hr ho hk
    · exact dcf_90 hlive hp hr ho hk
    · exact dcf_91 hlive hp hr ho hk
    · exact dcf_92 hlive hp hr ho hk
    · exact dcf_93 hlive hp hr ho hk
    · exact dcf_94 hlive hp hr ho hk
    · exact dcf_95 hlive hp hr ho hk
    · exact dcf_96 hlive hp hr ho hk
    · exact dcf_97 hlive hp hr ho hk
    · exact dcf_98 hlive hp hr ho hk
    · exact dcf_99 hlive hp hr ho hk
    · exact dcf_100 hlive hp hr ho hk
    · exact dcf_101 hlive hp hr ho hk
    · exact dcf_102 hlive hp hr ho hk
    · exact dcf_103 hlive hp hr ho hk
    · exact dcf_104 hlive hp hr ho hk
    · exact dcf_105 hlive hp hr ho hk
    · exact dcf_106 hlive hp hr ho hk
    · exact dcf_107 hlive hp hr ho hk
    · exact dcf_108 hlive hp hr ho hk
    · exact dcf_109 hlive hp hr ho hk
    · exact dcf_110 hlive hp hr ho hk
    · exact dcf_111 hlive hp hr ho hk
    · exact dcf_112 hlive hp hr ho hk
    · exact dcf_113 hlive hp hr ho hk
    · exact dcf_114 hlive hp hr ho hk
    · exact dcf_115 hlive hp hr ho hk
    · exact dcf_116 hlive hp hr ho hk
    · exact dcf_117 hlive hp hr ho hk
    · exact dcf_118 hlive hp hr ho hk
    · exact dcf_119 hlive hp hr ho hk
    · exact dcf_120 hlive hp hr ho hk
    · exact dcf_121 hlive hp hr ho hk
    · exact dcf_122 hlive hp hr ho hk
    · exact dcf_123 hlive hp hr ho hk
    · exact dcf_124 hlive hp hr ho hk
    · exact dcf_125 hlive hp hr ho hk
    · exact dcf_126 hlive hp hr ho hk
  · exact dcf_out hlive hp hr hout hk

/-- **`dc_func (c, peekc, negcmp)`** at `0x80000b9c`, every character. -/
theorem dc_func_spec {live S : Nat → Prop}
    {Q : String → (Nat → BitVec 64) → (Nat → BitVec 8) → Prop}
    (hlive : ∀ p ∈ dcText, live p.1) {t0 : String} {sp W : Nat} {M : Mem} {H : Heap}
    {F : List Blk} {L : List NumObj} {C : BcConsts} {G : DcG} {hs : List GV} {st : St}
    {c : Nat} {peek : Option Nat} {neg : Bool} {R : Nat → BitVec 64}
    (hp : FnPre S sp W M H F L C G hs st c peek) (hr : FnRegs R sp c peek neg)
    (ho : FnOom live S Q sp W M)
    (hk : FnK live S Q (leakAllow c) t0 st (dcFunc 70 st c peek neg) G hs sp W M R) :
    DWO live S Q (t0 ++ Dc.outStr st.out) 0x80000b9c#64 R M :=
  dc_func_spec_done hlive (by
    by_cases h : 9 ≤ c ∧ c ≤ 126
    · have hall : ∀ c, c < 127 → 9 ≤ c → c ∈ fnDone := by decide +kernel
      exact .inl (hall c (by omega) h.1)
    · exact .inr (by omega)) hp hr ho hk

end Dc.Mach
