name = "Vsa"
defaultTargets = ["Vsa"]

[[lean_lib]]
name = "Vsa"
leanOptions.backward.isDefEq.respectTransparency = false

[[lean_exe]]
name = "vsa_run"
root = "VsaRun"

[[lean_lib]]
name = "VsaIris"

[[require]]
name = "lean-riscv"
path = "riscv-lean/lean_emulator"

[[require]]
name = "iris"
git = "https://github.com/leanprover-community/iris-lean"
rev = "740e2c4a9c672c61d76ad2f9c478c922f7461cf6"
subDir = "Iris"

[[lean_lib]]
name = "VsaBoot"

[[lean_lib]]
name = "Dc"
leanOptions.backward.isDefEq.respectTransparency = false
