import Dc.Mach.Bc.KaraScan

/-!
# `_bc_rec_mul`'s inlined `bc_is_zero` tests (generated)

Generated by `scripts/dc/gen_kara_scan.py`; do not hand-edit.
-/

namespace Dc.Mach

open Vsa.MemRepr Vsa.Sim VsaIris VsaIris.Inst VsaIris.Sym VsaIris.MallocFast
open LeanRV64DExecutable LeanRV64DExecutable.Functions Sail

set_option linter.unusedSimpArgs false

/-- The digit scan at `0x80004f98`: the first `i` digits zero, `k + 1` left. -/
theorem kscan_80004f98 {live : Nat → Prop} {S : Nat → Prop}
    {Q : (Nat → BitVec 64) → (Nat → BitVec 8) → Prop} (hlive : ∀ p ∈ dcText, live p.1)
    {M : Mem} {o : NumRep} {Rb : Nat → BitVec 64} (hS : HeapOwn S) (hn : NumAt M o)
    (hz : ∀ R', Keeps [13, 14, 15] R' Rb → (∀ j, j < o.len + o.scale → o.ds.getD j 0 = 0) →
      DW live S Q 0x800054bc#64 R' M)
    (hnz : ∀ R', Keeps [13, 14, 15] R' Rb → DW live S Q 0x80004fa0#64 R' M) :
    ∀ k i (R : Nat → BitVec 64), o.len + o.scale = i + k + 1 → (∀ j, j < i → o.ds.getD j 0 = 0) →
      Keeps [13, 14, 15] R Rb → R 15 = BitVec.ofNat 64 (k + 1) → R 14 = BitVec.ofNat 64 (o.val + i) →
      DW live S Q 0x80004f98#64 R M := by
  num_facts hn
  intro k
  induction k with
  | zero =>
    intro i R hi hz0 kk hc hp
    have hl := hn.lbu (i := i) (by omega)
    have hd := hn.getD_lt i
    bc_run hlive hS [hc, hp, hl] at 0x80004f8c 0x80004fa0
    all_goals first | exact acc_heap hS (by omega) (by omega) | skip
    · intro h0
      bsimp [ofNat_eq_zero_iff (show o.ds.getD i 0 < 2 ^ 64 by omega)] at h0
      bc_run hlive hS [hc, hp] at 0x800054bc 0x80004f98
      exact hz _ (by keeps_tac kk) fun j hj => by
        rcases Nat.lt_or_ge j i with h1 | h1
        · exact hz0 j h1
        · rw [show j = i by omega]; exact h0
    · intro _; exact hnz _ (by keeps_tac kk)
  | succ k ih =>
    intro i R hi hz0 kk hc hp
    have hl := hn.lbu (i := i) (by omega)
    have hd := hn.getD_lt i
    bc_run hlive hS [hc, hp, hl] at 0x80004f8c 0x80004fa0
    all_goals first | exact acc_heap hS (by omega) (by omega) | skip
    · intro h0
      bsimp [ofNat_eq_zero_iff (show o.ds.getD i 0 < 2 ^ 64 by omega)] at h0
      bc_run hlive hS [hc, hp] at 0x800054bc 0x80004f98
      · intro hc'
        exact absurd ((ofNat_eq_zero_iff (by omega)).mp hc') (by omega)
      · intro _
        refine ih (i + 1) _ (by omega) (fun j hj => ?_) (by keeps_tac kk)
          (by bsimp [show k + 1 + 1 - 1 = k + 1 by omega]) (by bsimp [Nat.add_assoc])
        rcases Nat.lt_or_ge j i with h1 | h1
        · exact hz0 j h1
        · rw [show j = i by omega]; exact h0
    · intro _; exact hnz _ (by keeps_tac kk)

/-- **The `bc_is_zero` test at `0x80004f70`** of the handle in `x24`: `_zero_`
(`x17`) or a number with all digits zero reaches `0x800054bc`, any other number
`0x80004fa0`. -/
theorem kzero_80004f70 {live : Nat → Prop} {S : Nat → Prop}
    {Q : (Nat → BitVec 64) → (Nat → BitVec 8) → Prop} (hlive : ∀ p ∈ dcText, live p.1)
    {M : Mem} {R : Nat → BitVec 64} {z : NumObj} {h : Hd} (hS : HeapOwn S)
    (hob : R 24 = BitVec.ofNat 64 (Hd.p z h)) (hzr : R 17 = BitVec.ofNat 64 z.rep.p)
    (hzb : z.rep.p < 2 ^ 64) (hx : ∀ x, h = some x → NumAt M x.rep ∧ x.rep.p ≠ z.rep.p)
    (hz : ∀ R', Keeps [13, 14, 15] R' R → HdZero h → DW live S Q 0x800054bc#64 R' M)
    (hnz : ∀ R', Keeps [13, 14, 15] R' R → DW live S Q 0x80004fa0#64 R' M) :
    DW live S Q 0x80004f70#64 R M := by
  have htx : tohostAddr = 0x8001ad00 := rfl
  cases h with
  | none =>
    simp only [Hd.p] at hob
    bc_run hlive (fun _ _ _ => hS _ (by assumption) (by assumption)) [hob, hzr] at 0x800054bc
    exact hz _ (by keeps_tac Keeps.refl _ _) fun x hx => nomatch hx
  | some x =>
    obtain ⟨hn, hne⟩ := hx x rfl
    simp only [Hd.p] at hob
    num_facts hn
    have hne' : ¬ BitVec.ofNat 64 x.rep.p = BitVec.ofNat 64 z.rep.p := fun e =>
      hne ((ofNat_eq_iff (by omega) hzb).mp e)
    have hl := hn.len; have hsc := hn.scale; have hv := hn.value
    bc_run hlive hS [hob, hzr, hne', hl, hsc, hv, addw_ofNat] at 0x80004f98
    all_goals first | exact acc_heap hS (by omega) (by omega) | skip
    bc_run hlive hS [hob, hzr, hne', hl, hsc, hv, addw_ofNat] at 0x80004f98
    all_goals first | exact acc_heap hS (by omega) (by omega) | skip
    · intro hc; exact absurd hc (not_blez (by omega) (by omega))
    intro _
    bc_run hlive hS [hob, hzr, hne', hl, hsc, hv, addw_ofNat] at 0x80004f98
    all_goals first | exact acc_heap hS (by omega) (by omega) | skip
    refine kscan_80004f98 hlive hS hn (Rb := R) (fun R' kk hd => hz R' kk fun y hy => by cases hy; exact hd)
      hnz (x.rep.len + x.rep.scale - 1) 0 _ (by omega) (fun j hj => absurd hj (Nat.not_lt_zero _)) (by keeps_tac Keeps.refl _ _) ?_ ?_
    · bsimp [show x.rep.scale + x.rep.len = x.rep.len + x.rep.scale - 1 + 1 by omega]
    · bsimp []

/-- The digit scan at `0x80004fd0`: the first `i` digits zero, `k + 1` left. -/
theorem kscan_80004fd0 {live : Nat → Prop} {S : Nat → Prop}
    {Q : (Nat → BitVec 64) → (Nat → BitVec 8) → Prop} (hlive : ∀ p ∈ dcText, live p.1)
    {M : Mem} {o : NumRep} {Rb : Nat → BitVec 64} (hS : HeapOwn S) (hn : NumAt M o)
    (hz : ∀ R', Keeps [14, 15, 26] R' Rb → (∀ j, j < o.len + o.scale → o.ds.getD j 0 = 0) →
      DW live S Q 0x800054bc#64 R' M)
    (hnz : ∀ R', Keeps [14, 15, 26] R' Rb → DW live S Q 0x80004fd8#64 R' M) :
    ∀ k i (R : Nat → BitVec 64), o.len + o.scale = i + k + 1 → (∀ j, j < i → o.ds.getD j 0 = 0) →
      Keeps [14, 15, 26] R Rb → R 26 = BitVec.ofNat 64 (k + 1) → R 15 = BitVec.ofNat 64 (o.val + i) →
      DW live S Q 0x80004fd0#64 R M := by
  num_facts hn
  intro k
  induction k with
  | zero =>
    intro i R hi hz0 kk hc hp
    have hl := hn.lbu (i := i) (by omega)
    have hd := hn.getD_lt i
    bc_run hlive hS [hc, hp, hl] at 0x80004fc4 0x80004fd8
    all_goals first | exact acc_heap hS (by omega) (by omega) | skip
    · intro h0
      bsimp [ofNat_eq_zero_iff (show o.ds.getD i 0 < 2 ^ 64 by omega)] at h0
      bc_run hlive hS [hc, hp] at 0x800054bc 0x80004fd0
      exact hz _ (by keeps_tac kk) fun j hj => by
        rcases Nat.lt_or_ge j i with h1 | h1
        · exact hz0 j h1
        · rw [show j = i by omega]; exact h0
    · intro _; exact hnz _ (by keeps_tac kk)
  | succ k ih =>
    intro i R hi hz0 kk hc hp
    have hl := hn.lbu (i := i) (by omega)
    have hd := hn.getD_lt i
    bc_run hlive hS [hc, hp, hl] at 0x80004fc4 0x80004fd8
    all_goals first | exact acc_heap hS (by omega) (by omega) | skip
    · intro h0
      bsimp [ofNat_eq_zero_iff (show o.ds.getD i 0 < 2 ^ 64 by omega)] at h0
      bc_run hlive hS [hc, hp] at 0x800054bc 0x80004fd0
      · intro hc'
        exact absurd ((ofNat_eq_zero_iff (by omega)).mp hc') (by omega)
      · intro _
        refine ih (i + 1) _ (by omega) (fun j hj => ?_) (by keeps_tac kk)
          (by bsimp [show k + 1 + 1 - 1 = k + 1 by omega]) (by bsimp [Nat.add_assoc])
        rcases Nat.lt_or_ge j i with h1 | h1
        · exact hz0 j h1
        · rw [show j = i by omega]; exact h0
    · intro _; exact hnz _ (by keeps_tac kk)

/-- **The `bc_is_zero` test at `0x80004fa0`** of the handle in `x27`: `_zero_`
(`x17`) or a number with all digits zero reaches `0x800054bc`, any other number
`0x80004fd8`. -/
theorem kzero_80004fa0 {live : Nat → Prop} {S : Nat → Prop}
    {Q : (Nat → BitVec 64) → (Nat → BitVec 8) → Prop} (hlive : ∀ p ∈ dcText, live p.1)
    {M : Mem} {R : Nat → BitVec 64} {z : NumObj} {h : Hd} (hS : HeapOwn S)
    (hob : R 27 = BitVec.ofNat 64 (Hd.p z h)) (hzr : R 17 = BitVec.ofNat 64 z.rep.p)
    (hzb : z.rep.p < 2 ^ 64) (hx : ∀ x, h = some x → NumAt M x.rep ∧ x.rep.p ≠ z.rep.p)
    (hz : ∀ R', Keeps [14, 15, 26] R' R → HdZero h → DW live S Q 0x800054bc#64 R' M)
    (hnz : ∀ R', Keeps [14, 15, 26] R' R → DW live S Q 0x80004fd8#64 R' M) :
    DW live S Q 0x80004fa0#64 R M := by
  have htx : tohostAddr = 0x8001ad00 := rfl
  cases h with
  | none =>
    simp only [Hd.p] at hob
    bc_run hlive (fun _ _ _ => hS _ (by assumption) (by assumption)) [hob, hzr] at 0x800054bc
    exact hz _ (by keeps_tac Keeps.refl _ _) fun x hx => nomatch hx
  | some x =>
    obtain ⟨hn, hne⟩ := hx x rfl
    simp only [Hd.p] at hob
    num_facts hn
    have hne' : ¬ BitVec.ofNat 64 x.rep.p = BitVec.ofNat 64 z.rep.p := fun e =>
      hne ((ofNat_eq_iff (by omega) hzb).mp e)
    have hl := hn.len; have hsc := hn.scale; have hv := hn.value
    bc_run hlive hS [hob, hzr, hne', hl, hsc, hv, addw_ofNat] at 0x80004fd0
    all_goals first | exact acc_heap hS (by omega) (by omega) | skip
    bc_run hlive hS [hob, hzr, hne', hl, hsc, hv, addw_ofNat] at 0x80004fd0
    all_goals first | exact acc_heap hS (by omega) (by omega) | skip
    · intro hc; exact absurd hc (not_blez (by omega) (by omega))
    intro _
    bc_run hlive hS [hob, hzr, hne', hl, hsc, hv, addw_ofNat] at 0x80004fd0
    all_goals first | exact acc_heap hS (by omega) (by omega) | skip
    refine kscan_80004fd0 hlive hS hn (Rb := R) (fun R' kk hd => hz R' kk fun y hy => by cases hy; exact hd)
      hnz (x.rep.len + x.rep.scale - 1) 0 _ (by omega) (fun j hj => absurd hj (Nat.not_lt_zero _)) (by keeps_tac Keeps.refl _ _) ?_ ?_
    · bsimp [show x.rep.scale + x.rep.len = x.rep.len + x.rep.scale - 1 + 1 by omega]
    · bsimp []

/-- The digit scan at `0x80005078`: the first `i` digits zero, `k + 1` left. -/
theorem kscan_80005078 {live : Nat → Prop} {S : Nat → Prop}
    {Q : (Nat → BitVec 64) → (Nat → BitVec 8) → Prop} (hlive : ∀ p ∈ dcText, live p.1)
    {M : Mem} {o : NumRep} {Rb : Nat → BitVec 64} (hS : HeapOwn S) (hn : NumAt M o)
    (hz : ∀ R', Keeps [13, 14, 15] R' Rb → (∀ j, j < o.len + o.scale → o.ds.getD j 0 = 0) →
      DW live S Q 0x800054a8#64 R' M)
    (hnz : ∀ R', Keeps [13, 14, 15] R' Rb → DW live S Q 0x80005080#64 R' M) :
    ∀ k i (R : Nat → BitVec 64), o.len + o.scale = i + k + 1 → (∀ j, j < i → o.ds.getD j 0 = 0) →
      Keeps [13, 14, 15] R Rb → R 15 = BitVec.ofNat 64 (k + 1) → R 14 = BitVec.ofNat 64 (o.val + i) →
      DW live S Q 0x80005078#64 R M := by
  num_facts hn
  intro k
  induction k with
  | zero =>
    intro i R hi hz0 kk hc hp
    have hl := hn.lbu (i := i) (by omega)
    have hd := hn.getD_lt i
    bc_run hlive hS [hc, hp, hl] at 0x8000506c 0x80005080
    all_goals first | exact acc_heap hS (by omega) (by omega) | skip
    · intro h0
      bsimp [ofNat_eq_zero_iff (show o.ds.getD i 0 < 2 ^ 64 by omega)] at h0
      bc_run hlive hS [hc, hp] at 0x800054a8 0x80005078
      exact hz _ (by keeps_tac kk) fun j hj => by
        rcases Nat.lt_or_ge j i with h1 | h1
        · exact hz0 j h1
        · rw [show j = i by omega]; exact h0
    · intro _; exact hnz _ (by keeps_tac kk)
  | succ k ih =>
    intro i R hi hz0 kk hc hp
    have hl := hn.lbu (i := i) (by omega)
    have hd := hn.getD_lt i
    bc_run hlive hS [hc, hp, hl] at 0x8000506c 0x80005080
    all_goals first | exact acc_heap hS (by omega) (by omega) | skip
    · intro h0
      bsimp [ofNat_eq_zero_iff (show o.ds.getD i 0 < 2 ^ 64 by omega)] at h0
      bc_run hlive hS [hc, hp] at 0x800054a8 0x80005078
      · intro hc'
        exact absurd ((ofNat_eq_zero_iff (by omega)).mp hc') (by omega)
      · intro _
        refine ih (i + 1) _ (by omega) (fun j hj => ?_) (by keeps_tac kk)
          (by bsimp [show k + 1 + 1 - 1 = k + 1 by omega]) (by bsimp [Nat.add_assoc])
        rcases Nat.lt_or_ge j i with h1 | h1
        · exact hz0 j h1
        · rw [show j = i by omega]; exact h0
    · intro _; exact hnz _ (by keeps_tac kk)

/-- **The `bc_is_zero` test at `0x80005050`** of the handle in `x21`: `_zero_`
(`x12`) or a number with all digits zero reaches `0x800054a8`, any other number
`0x80005080`. -/
theorem kzero_80005050 {live : Nat → Prop} {S : Nat → Prop}
    {Q : (Nat → BitVec 64) → (Nat → BitVec 8) → Prop} (hlive : ∀ p ∈ dcText, live p.1)
    {M : Mem} {R : Nat → BitVec 64} {z : NumObj} {h : Hd} (hS : HeapOwn S)
    (hob : R 21 = BitVec.ofNat 64 (Hd.p z h)) (hzr : R 12 = BitVec.ofNat 64 z.rep.p)
    (hzb : z.rep.p < 2 ^ 64) (hx : ∀ x, h = some x → NumAt M x.rep ∧ x.rep.p ≠ z.rep.p)
    (hz : ∀ R', Keeps [13, 14, 15] R' R → HdZero h → DW live S Q 0x800054a8#64 R' M)
    (hnz : ∀ R', Keeps [13, 14, 15] R' R → DW live S Q 0x80005080#64 R' M) :
    DW live S Q 0x80005050#64 R M := by
  have htx : tohostAddr = 0x8001ad00 := rfl
  cases h with
  | none =>
    simp only [Hd.p] at hob
    bc_run hlive (fun _ _ _ => hS _ (by assumption) (by assumption)) [hob, hzr] at 0x800054a8
    exact hz _ (by keeps_tac Keeps.refl _ _) fun x hx => nomatch hx
  | some x =>
    obtain ⟨hn, hne⟩ := hx x rfl
    simp only [Hd.p] at hob
    num_facts hn
    have hne' : ¬ BitVec.ofNat 64 x.rep.p = BitVec.ofNat 64 z.rep.p := fun e =>
      hne ((ofNat_eq_iff (by omega) hzb).mp e)
    have hl := hn.len; have hsc := hn.scale; have hv := hn.value
    bc_run hlive hS [hob, hzr, hne', hl, hsc, hv, addw_ofNat] at 0x80005078
    all_goals first | exact acc_heap hS (by omega) (by omega) | skip
    bc_run hlive hS [hob, hzr, hne', hl, hsc, hv, addw_ofNat] at 0x80005078
    all_goals first | exact acc_heap hS (by omega) (by omega) | skip
    · intro hc; exact absurd hc (not_blez (by omega) (by omega))
    intro _
    bc_run hlive hS [hob, hzr, hne', hl, hsc, hv, addw_ofNat] at 0x80005078
    all_goals first | exact acc_heap hS (by omega) (by omega) | skip
    refine kscan_80005078 hlive hS hn (Rb := R) (fun R' kk hd => hz R' kk fun y hy => by cases hy; exact hd)
      hnz (x.rep.len + x.rep.scale - 1) 0 _ (by omega) (fun j hj => absurd hj (Nat.not_lt_zero _)) (by keeps_tac Keeps.refl _ _) ?_ ?_
    · bsimp [show x.rep.scale + x.rep.len = x.rep.len + x.rep.scale - 1 + 1 by omega]
    · bsimp []

/-- The digit scan at `0x800050b0`: the first `i` digits zero, `k + 1` left. -/
theorem kscan_800050b0 {live : Nat → Prop} {S : Nat → Prop}
    {Q : (Nat → BitVec 64) → (Nat → BitVec 8) → Prop} (hlive : ∀ p ∈ dcText, live p.1)
    {M : Mem} {o : NumRep} {Rb : Nat → BitVec 64} (hS : HeapOwn S) (hn : NumAt M o)
    (hz : ∀ R', Keeps [13, 14, 15] R' Rb → (∀ j, j < o.len + o.scale → o.ds.getD j 0 = 0) →
      DW live S Q 0x800054a8#64 R' M)
    (hnz : ∀ R', Keeps [13, 14, 15] R' Rb → DW live S Q 0x800050b8#64 R' M) :
    ∀ k i (R : Nat → BitVec 64), o.len + o.scale = i + k + 1 → (∀ j, j < i → o.ds.getD j 0 = 0) →
      Keeps [13, 14, 15] R Rb → R 15 = BitVec.ofNat 64 (k + 1) → R 14 = BitVec.ofNat 64 (o.val + i) →
      DW live S Q 0x800050b0#64 R M := by
  num_facts hn
  intro k
  induction k with
  | zero =>
    intro i R hi hz0 kk hc hp
    have hl := hn.lbu (i := i) (by omega)
    have hd := hn.getD_lt i
    bc_run hlive hS [hc, hp, hl] at 0x800050a4 0x800050b8
    all_goals first | exact acc_heap hS (by omega) (by omega) | skip
    · intro h0
      bsimp [ofNat_eq_zero_iff (show o.ds.getD i 0 < 2 ^ 64 by omega)] at h0
      bc_run hlive hS [hc, hp] at 0x800054a8 0x800050b0
      exact hz _ (by keeps_tac kk) fun j hj => by
        rcases Nat.lt_or_ge j i with h1 | h1
        · exact hz0 j h1
        · rw [show j = i by omega]; exact h0
    · intro _; exact hnz _ (by keeps_tac kk)
  | succ k ih =>
    intro i R hi hz0 kk hc hp
    have hl := hn.lbu (i := i) (by omega)
    have hd := hn.getD_lt i
    bc_run hlive hS [hc, hp, hl] at 0x800050a4 0x800050b8
    all_goals first | exact acc_heap hS (by omega) (by omega) | skip
    · intro h0
      bsimp [ofNat_eq_zero_iff (show o.ds.getD i 0 < 2 ^ 64 by omega)] at h0
      bc_run hlive hS [hc, hp] at 0x800054a8 0x800050b0
      · intro hc'
        exact absurd ((ofNat_eq_zero_iff (by omega)).mp hc') (by omega)
      · intro _
        refine ih (i + 1) _ (by omega) (fun j hj => ?_) (by keeps_tac kk)
          (by bsimp [show k + 1 + 1 - 1 = k + 1 by omega]) (by bsimp [Nat.add_assoc])
        rcases Nat.lt_or_ge j i with h1 | h1
        · exact hz0 j h1
        · rw [show j = i by omega]; exact h0
    · intro _; exact hnz _ (by keeps_tac kk)

/-- **The `bc_is_zero` test at `0x80005080`** of the handle in `x23`: `_zero_`
(`x12`) or a number with all digits zero reaches `0x800054a8`, any other number
`0x800050b8`. -/
theorem kzero_80005080 {live : Nat → Prop} {S : Nat → Prop}
    {Q : (Nat → BitVec 64) → (Nat → BitVec 8) → Prop} (hlive : ∀ p ∈ dcText, live p.1)
    {M : Mem} {R : Nat → BitVec 64} {z : NumObj} {h : Hd} (hS : HeapOwn S)
    (hob : R 23 = BitVec.ofNat 64 (Hd.p z h)) (hzr : R 12 = BitVec.ofNat 64 z.rep.p)
    (hzb : z.rep.p < 2 ^ 64) (hx : ∀ x, h = some x → NumAt M x.rep ∧ x.rep.p ≠ z.rep.p)
    (hz : ∀ R', Keeps [13, 14, 15] R' R → HdZero h → DW live S Q 0x800054a8#64 R' M)
    (hnz : ∀ R', Keeps [13, 14, 15] R' R → DW live S Q 0x800050b8#64 R' M) :
    DW live S Q 0x80005080#64 R M := by
  have htx : tohostAddr = 0x8001ad00 := rfl
  cases h with
  | none =>
    simp only [Hd.p] at hob
    bc_run hlive (fun _ _ _ => hS _ (by assumption) (by assumption)) [hob, hzr] at 0x800054a8
    exact hz _ (by keeps_tac Keeps.refl _ _) fun x hx => nomatch hx
  | some x =>
    obtain ⟨hn, hne⟩ := hx x rfl
    simp only [Hd.p] at hob
    num_facts hn
    have hne' : ¬ BitVec.ofNat 64 x.rep.p = BitVec.ofNat 64 z.rep.p := fun e =>
      hne ((ofNat_eq_iff (by omega) hzb).mp e)
    have hl := hn.len; have hsc := hn.scale; have hv := hn.value
    bc_run hlive hS [hob, hzr, hne', hl, hsc, hv, addw_ofNat] at 0x800050b0
    all_goals first | exact acc_heap hS (by omega) (by omega) | skip
    bc_run hlive hS [hob, hzr, hne', hl, hsc, hv, addw_ofNat] at 0x800050b0
    all_goals first | exact acc_heap hS (by omega) (by omega) | skip
    · intro hc; exact absurd hc (not_blez (by omega) (by omega))
    intro _
    bc_run hlive hS [hob, hzr, hne', hl, hsc, hv, addw_ofNat] at 0x800050b0
    all_goals first | exact acc_heap hS (by omega) (by omega) | skip
    refine kscan_800050b0 hlive hS hn (Rb := R) (fun R' kk hd => hz R' kk fun y hy => by cases hy; exact hd)
      hnz (x.rep.len + x.rep.scale - 1) 0 _ (by omega) (fun j hj => absurd hj (Nat.not_lt_zero _)) (by keeps_tac Keeps.refl _ _) ?_ ?_
    · bsimp [show x.rep.scale + x.rep.len = x.rep.len + x.rep.scale - 1 + 1 by omega]
    · bsimp []

/-- The digit scan at `0x800050fc`: the first `i` digits zero, `k + 1` left. -/
theorem kscan_800050fc {live : Nat → Prop} {S : Nat → Prop}
    {Q : (Nat → BitVec 64) → (Nat → BitVec 8) → Prop} (hlive : ∀ p ∈ dcText, live p.1)
    {M : Mem} {o : NumRep} {Rb : Nat → BitVec 64} (hS : HeapOwn S) (hn : NumAt M o)
    (hz : ∀ R', Keeps [11, 13, 14, 15] R' Rb → (∀ j, j < o.len + o.scale → o.ds.getD j 0 = 0) →
      DW live S Q 0x80005440#64 R' M)
    (hnz : ∀ R', Keeps [11, 13, 14, 15] R' Rb → DW live S Q 0x80005104#64 R' M) :
    ∀ k i (R : Nat → BitVec 64), o.len + o.scale = i + k + 1 → (∀ j, j < i → o.ds.getD j 0 = 0) →
      Keeps [11, 13, 14, 15] R Rb → R 15 = BitVec.ofNat 64 (k + 1) → R 14 = BitVec.ofNat 64 (o.val + i) →
      DW live S Q 0x800050fc#64 R M := by
  num_facts hn
  intro k
  induction k with
  | zero =>
    intro i R hi hz0 kk hc hp
    have hl := hn.lbu (i := i) (by omega)
    have hd := hn.getD_lt i
    bc_run hlive hS [hc, hp, hl] at 0x800050f0 0x80005104
    all_goals first | exact acc_heap hS (by omega) (by omega) | skip
    · intro h0
      bsimp [ofNat_eq_zero_iff (show o.ds.getD i 0 < 2 ^ 64 by omega)] at h0
      bc_run hlive hS [hc, hp] at 0x80005440 0x800050fc
      exact hz _ (by keeps_tac kk) fun j hj => by
        rcases Nat.lt_or_ge j i with h1 | h1
        · exact hz0 j h1
        · rw [show j = i by omega]; exact h0
    · intro _; exact hnz _ (by keeps_tac kk)
  | succ k ih =>
    intro i R hi hz0 kk hc hp
    have hl := hn.lbu (i := i) (by omega)
    have hd := hn.getD_lt i
    bc_run hlive hS [hc, hp, hl] at 0x800050f0 0x80005104
    all_goals first | exact acc_heap hS (by omega) (by omega) | skip
    · intro h0
      bsimp [ofNat_eq_zero_iff (show o.ds.getD i 0 < 2 ^ 64 by omega)] at h0
      bc_run hlive hS [hc, hp] at 0x80005440 0x800050fc
      · intro hc'
        exact absurd ((ofNat_eq_zero_iff (by omega)).mp hc') (by omega)
      · intro _
        refine ih (i + 1) _ (by omega) (fun j hj => ?_) (by keeps_tac kk)
          (by bsimp [show k + 1 + 1 - 1 = k + 1 by omega]) (by bsimp [Nat.add_assoc])
        rcases Nat.lt_or_ge j i with h1 | h1
        · exact hz0 j h1
        · rw [show j = i by omega]; exact h0
    · intro _; exact hnz _ (by keeps_tac kk)

/-- **The `bc_is_zero` test at `0x800050d4`** of the handle in `x19`: `_zero_`
(`x12`) or a number with all digits zero reaches `0x80005440`, any other number
`0x80005104`. -/
theorem kzero_800050d4 {live : Nat → Prop} {S : Nat → Prop}
    {Q : (Nat → BitVec 64) → (Nat → BitVec 8) → Prop} (hlive : ∀ p ∈ dcText, live p.1)
    {M : Mem} {R : Nat → BitVec 64} {z : NumObj} {h : Hd} (hS : HeapOwn S)
    (hob : R 19 = BitVec.ofNat 64 (Hd.p z h)) (hzr : R 12 = BitVec.ofNat 64 z.rep.p)
    (hzb : z.rep.p < 2 ^ 64) (hx : ∀ x, h = some x → NumAt M x.rep ∧ x.rep.p ≠ z.rep.p)
    (hz : ∀ R', Keeps [11, 13, 14, 15] R' R → HdZero h → DW live S Q 0x80005440#64 R' M)
    (hnz : ∀ R', Keeps [11, 13, 14, 15] R' R → DW live S Q 0x80005104#64 R' M) :
    DW live S Q 0x800050d4#64 R M := by
  have htx : tohostAddr = 0x8001ad00 := rfl
  cases h with
  | none =>
    simp only [Hd.p] at hob
    bc_run hlive (fun _ _ _ => hS _ (by assumption) (by assumption)) [hob, hzr] at 0x80005440
    exact hz _ (by keeps_tac Keeps.refl _ _) fun x hx => nomatch hx
  | some x =>
    obtain ⟨hn, hne⟩ := hx x rfl
    simp only [Hd.p] at hob
    num_facts hn
    have hne' : ¬ BitVec.ofNat 64 x.rep.p = BitVec.ofNat 64 z.rep.p := fun e =>
      hne ((ofNat_eq_iff (by omega) hzb).mp e)
    have hl := hn.len; have hsc := hn.scale; have hv := hn.value
    bc_run hlive hS [hob, hzr, hne', hl, hsc, hv, addw_ofNat] at 0x800050fc
    all_goals first | exact acc_heap hS (by omega) (by omega) | skip
    bc_run hlive hS [hob, hzr, hne', hl, hsc, hv, addw_ofNat] at 0x800050fc
    all_goals first | exact acc_heap hS (by omega) (by omega) | skip
    · intro hc; exact absurd hc (not_blez (by omega) (by omega))
    intro _
    bc_run hlive hS [hob, hzr, hne', hl, hsc, hv, addw_ofNat] at 0x800050fc
    all_goals first | exact acc_heap hS (by omega) (by omega) | skip
    refine kscan_800050fc hlive hS hn (Rb := R) (fun R' kk hd => hz R' kk fun y hy => by cases hy; exact hd)
      hnz (x.rep.len + x.rep.scale - 1) 0 _ (by omega) (fun j hj => absurd hj (Nat.not_lt_zero _)) (by keeps_tac Keeps.refl _ _) ?_ ?_
    · bsimp [show x.rep.scale + x.rep.len = x.rep.len + x.rep.scale - 1 + 1 by omega]
    · bsimp []

/-- The digit scan at `0x80005134`: the first `i` digits zero, `k + 1` left. -/
theorem kscan_80005134 {live : Nat → Prop} {S : Nat → Prop}
    {Q : (Nat → BitVec 64) → (Nat → BitVec 8) → Prop} (hlive : ∀ p ∈ dcText, live p.1)
    {M : Mem} {o : NumRep} {Rb : Nat → BitVec 64} (hS : HeapOwn S) (hn : NumAt M o)
    (hz : ∀ R', Keeps [10, 13, 14, 15] R' Rb → (∀ j, j < o.len + o.scale → o.ds.getD j 0 = 0) →
      DW live S Q 0x80005440#64 R' M)
    (hnz : ∀ R', Keeps [10, 13, 14, 15] R' Rb → DW live S Q 0x8000513c#64 R' M) :
    ∀ k i (R : Nat → BitVec 64), o.len + o.scale = i + k + 1 → (∀ j, j < i → o.ds.getD j 0 = 0) →
      Keeps [10, 13, 14, 15] R Rb → R 15 = BitVec.ofNat 64 (k + 1) → R 14 = BitVec.ofNat 64 (o.val + i) →
      DW live S Q 0x80005134#64 R M := by
  num_facts hn
  intro k
  induction k with
  | zero =>
    intro i R hi hz0 kk hc hp
    have hl := hn.lbu (i := i) (by omega)
    have hd := hn.getD_lt i
    bc_run hlive hS [hc, hp, hl] at 0x80005128 0x8000513c
    all_goals first | exact acc_heap hS (by omega) (by omega) | skip
    · intro h0
      bsimp [ofNat_eq_zero_iff (show o.ds.getD i 0 < 2 ^ 64 by omega)] at h0
      bc_run hlive hS [hc, hp] at 0x80005440 0x80005134
      exact hz _ (by keeps_tac kk) fun j hj => by
        rcases Nat.lt_or_ge j i with h1 | h1
        · exact hz0 j h1
        · rw [show j = i by omega]; exact h0
    · intro _; exact hnz _ (by keeps_tac kk)
  | succ k ih =>
    intro i R hi hz0 kk hc hp
    have hl := hn.lbu (i := i) (by omega)
    have hd := hn.getD_lt i
    bc_run hlive hS [hc, hp, hl] at 0x80005128 0x8000513c
    all_goals first | exact acc_heap hS (by omega) (by omega) | skip
    · intro h0
      bsimp [ofNat_eq_zero_iff (show o.ds.getD i 0 < 2 ^ 64 by omega)] at h0
      bc_run hlive hS [hc, hp] at 0x80005440 0x80005134
      · intro hc'
        exact absurd ((ofNat_eq_zero_iff (by omega)).mp hc') (by omega)
      · intro _
        refine ih (i + 1) _ (by omega) (fun j hj => ?_) (by keeps_tac kk)
          (by bsimp [show k + 1 + 1 - 1 = k + 1 by omega]) (by bsimp [Nat.add_assoc])
        rcases Nat.lt_or_ge j i with h1 | h1
        · exact hz0 j h1
        · rw [show j = i by omega]; exact h0
    · intro _; exact hnz _ (by keeps_tac kk)

/-- **The `bc_is_zero` test at `0x80005104`** of the handle in `x20`: `_zero_`
(`x12`) or a number with all digits zero reaches `0x80005440`, any other number
`0x8000513c`. -/
theorem kzero_80005104 {live : Nat → Prop} {S : Nat → Prop}
    {Q : (Nat → BitVec 64) → (Nat → BitVec 8) → Prop} (hlive : ∀ p ∈ dcText, live p.1)
    {M : Mem} {R : Nat → BitVec 64} {z : NumObj} {h : Hd} (hS : HeapOwn S)
    (hob : R 20 = BitVec.ofNat 64 (Hd.p z h)) (hzr : R 12 = BitVec.ofNat 64 z.rep.p)
    (hzb : z.rep.p < 2 ^ 64) (hx : ∀ x, h = some x → NumAt M x.rep ∧ x.rep.p ≠ z.rep.p)
    (hz : ∀ R', Keeps [10, 13, 14, 15] R' R → HdZero h → DW live S Q 0x80005440#64 R' M)
    (hnz : ∀ R', Keeps [10, 13, 14, 15] R' R → DW live S Q 0x8000513c#64 R' M) :
    DW live S Q 0x80005104#64 R M := by
  have htx : tohostAddr = 0x8001ad00 := rfl
  cases h with
  | none =>
    simp only [Hd.p] at hob
    bc_run hlive (fun _ _ _ => hS _ (by assumption) (by assumption)) [hob, hzr] at 0x80005440
    exact hz _ (by keeps_tac Keeps.refl _ _) fun x hx => nomatch hx
  | some x =>
    obtain ⟨hn, hne⟩ := hx x rfl
    simp only [Hd.p] at hob
    num_facts hn
    have hne' : ¬ BitVec.ofNat 64 x.rep.p = BitVec.ofNat 64 z.rep.p := fun e =>
      hne ((ofNat_eq_iff (by omega) hzb).mp e)
    have hl := hn.len; have hsc := hn.scale; have hv := hn.value
    bc_run hlive hS [hob, hzr, hne', hl, hsc, hv, addw_ofNat] at 0x80005134
    all_goals first | exact acc_heap hS (by omega) (by omega) | skip
    bc_run hlive hS [hob, hzr, hne', hl, hsc, hv, addw_ofNat] at 0x80005134
    all_goals first | exact acc_heap hS (by omega) (by omega) | skip
    · intro hc; exact absurd hc (not_blez (by omega) (by omega))
    intro _
    bc_run hlive hS [hob, hzr, hne', hl, hsc, hv, addw_ofNat] at 0x80005134
    all_goals first | exact acc_heap hS (by omega) (by omega) | skip
    refine kscan_80005134 hlive hS hn (Rb := R) (fun R' kk hd => hz R' kk fun y hy => by cases hy; exact hd)
      hnz (x.rep.len + x.rep.scale - 1) 0 _ (by omega) (fun j hj => absurd hj (Nat.not_lt_zero _)) (by keeps_tac Keeps.refl _ _) ?_ ?_
    · bsimp [show x.rep.scale + x.rep.len = x.rep.len + x.rep.scale - 1 + 1 by omega]
    · bsimp []

end Dc.Mach
