#!/usr/bin/env python3
"""Generate Dc/Mach/BootImageData.lean from the dc ELF's loader pieces.

Input: the TSV of `scripts/boot_elf_pieces.lean dc-port/dc-riscv-htif.elf`
(`<path>\t<seg|bob>\t<base>\t<hex bytes>`, in `initializeMemory`'s insertion
order). Output: the pieces `(base, size)`, the bytes below RAM
(`dcLowByte`) and the `.tohost`/`.data` piece (`dcDataByte`, offsets from
0x8001ad00) as packed little-endian naturals. The `.text`/`.rodata` piece is
`dcText` (`Dc/Mach/Code.lean`); the script buffer inside `.data` is replaced
by the program in `dcImageByte` (`BootImage.lean`).

  python3 -B scripts/dc/gen_dc_boot_image.py <pieces.tsv> [--check]
"""
import sys

OUT = "Dc/Mach/BootImageData.lean"
TEXT_BASE, TEXT_LEN = 0x80000000, 33304
DATA_BASE = 0x8001ad00
PAGE = 1024


def packed(bs):
    return "0x" + (bytes(reversed(bs)).hex() or "0")


def main():
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    check = "--check" in sys.argv
    rows = []
    for line in open(args[0]):
        parts = line.rstrip("\n").split("\t")
        if len(parts) < 3:
            continue
        hexs = parts[3] if len(parts) > 3 else ""
        rows.append((int(parts[2]), bytes.fromhex(hexs)))
    pieces = [(b, len(d)) for b, d in rows]
    low = [(b, d) for b, d in rows if b < 0x80000000 and len(d) > 0]
    data = [d for b, d in rows if b == DATA_BASE]
    text = [d for b, d in rows if b == TEXT_BASE]
    assert len(data) == 1 and len(text) == 1 and len(text[0]) == TEXT_LEN, "unexpected pieces"
    data = data[0]
    L = []
    L.append("-- Generated by scripts/dc/gen_dc_boot_image.py; do not edit.")
    L.append("import Dc.Mach.Code\n")
    L.append("/-! The dc ELF's loader pieces (`scripts/boot_elf_pieces.lean`). Packed data only. -/\n")
    L.append("namespace Dc.Mach\n")
    L.append("/-- The loader's pieces `(base, size)`, in `initializeMemory`'s insertion order. -/")
    L.append("def dcBootPieces : List (Nat × Nat) :=")
    L.append("  [" + ", ".join(f"(0x{b:x}, {n})" for b, n in pieces) + "]\n")
    for i, (b, d) in enumerate(low):
        L.append(f"private def dcLow{i} : Nat := {packed(d)}")
    conds = " else ".join(
        f"if 0x{b:x} ≤ x ∧ x < 0x{b + len(d):x} then BitVec.ofNat 8 (Nat.shiftRight dcLow{i} (8 * (x - 0x{b:x})))"
        for i, (b, d) in enumerate(low))
    L.append("\n/-- Loader bytes below RAM (ELF metadata the loader also inserts). -/")
    L.append(f"def dcLowByte (x : Nat) : BitVec 8 :=\n  {conds} else 0#8\n")
    npages = (len(data) + PAGE - 1) // PAGE
    for p in range(npages):
        L.append(f"private def dcDataPage{p} : Nat := {packed(data[p * PAGE:(p + 1) * PAGE])}")
    pconds = " else ".join(
        f"if o < {(p + 1) * PAGE} then BitVec.ofNat 8 (Nat.shiftRight dcDataPage{p} (8 * (o - {p * PAGE})))"
        for p in range(npages))
    L.append(f"\n/-- The `.tohost`/`.data` piece's byte at offset `o` from `0x{DATA_BASE:x}` ({len(data)} bytes). -/")
    L.append(f"def dcDataByte (o : Nat) : BitVec 8 :=\n  {pconds} else 0#8\n")
    L.append("end Dc.Mach")
    out = "\n".join(L) + "\n"
    if check:
        cur = open(OUT).read()
        if cur != out:
            print(f"{OUT} is stale"); sys.exit(1)
        print("ok"); return
    open(OUT, "w").write(out)


if __name__ == "__main__":
    main()
