#!/usr/bin/env python3
"""Generate Dc/Validation.lean: kernel-checked outputs of dc programs.

Each program is run on the RISC-V binary (`dc-port/dc-riscv-htif.elf` on
the proof's Sail RV64 model, `Vsa.runElf`), on the Lean interpreter
(`Dc.runOut`, line length 70) and on host GNU dc. The generator stops if
the three disagree; otherwise it emits

    theorem v_NN : Runs 70 PROG OUT ∧ ∀ o, Runs 70 PROG o → o = OUT :=
      runOut_spec (fuel := F) (by decide)

so the kernel checks that the semantics derives the binary's output and no
other.

    python3 scripts/dc/gen_validation.py --vsa-olean DIR --dc-olean DIR [--check]
"""

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import difftest  # noqa: E402
import elf_difftest  # noqa: E402

REPO = Path(__file__).resolve().parents[2]
OUT = REPO / "Dc" / "Validation.lean"

PROGRAMS = [
    ("hello", "[hello, world]p"),
    ("arith", "1 2+p 5 3-p 6 7*p 7 2/p _7 2/p 2k 7 3/p 2k _7 3%p 10 3~f"),
    ("scale", "1.5 2.25+p 1.50 2.2-p 0.1 0.2*p 2k 0.1 0.2*p 1.234 5.6789*p"),
    ("power", "2 10^p 2 _1^p 2k 3 _2^p 1.5 3^p _.1 3^p 3 5 7|p 4 13 497|p"),
    ("sqrt", "2v p 2k 2v p 0.0001v p 10k 1000000v p 0.25v p 144v p"),
    ("printing", "1.p .5p 0.00p _0p _ 5p 007p 0.10p [abc]p [a[b]c]p [a]n [b]n 10P"),
    ("length", "12345Zp .00012Zp 1.20Xp [abc]Zp [abc]Xp 0Zp 100Xp"),
    ("stack", "1 2 3 3R f c 1 2 3 _3R f c 1dp d+p z p c 1 2 r f"),
    ("ascii", "97a P 3a P 256 1+P [xyz]a P 65P 16706P"),
    ("obase", "2o 10p 0.5p 5.25p _6p 16o 255p 3.75p 20o 399p 1.5p 100o 12345.678p"),
    ("ibase", "2i 101p 1.1p 16i FFp A.8p"),
    ("params", "2k Kp 0k Kp Ip Op 1o Op 4294967297k Kp 2147483649k Kp"),
    ("compare", "[2p]sa 1 2<a 2 1<a 1 2>a 2 1>a 1 1!=a 1 2!=a 1 2!<a 2 1!<a"),
    ("registers", "5Sa 6Sa lap Lap Lap Lap f 7 3:b 3;bp 4;bp"),
    ("quit", "[1p q 2p]x 3p"),
    ("Q", "[[1p 2Q 5p]x 2p]x 3p [4p 1Q 5p]x 6p"),
    ("unimplemented", "y 1 2 f"),
    ("loop", "[d p 1- d 0<a]sa 5 lax"),
    ("factorial", "[d 1- d 1<f *]sf 10 lfx p 30 lfx p"),
    ("fibonacci", "0sa 1sb [la lb d sa + d sb p lc 1+ d sc 15>f]sf 0sc lfx"),
    ("gcd", "[d Sa % La r d 0<g]sg 1071 462 lgx r p 12345678 87654321 lgx r p"),
    ("sqrt2", "50k 2v p"),
    ("bigmul", "1234567890123456789012345678901234567890 987654321098765432109876543210*p"),
    ("wrap", "2 300^p"),
    ("tail", "[1+ d 1000>a]sa 0 lax p"),
]


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--vsa-olean", required=True)
    ap.add_argument("--dc-olean", required=True)
    ap.add_argument("--fuel", type=int, default=1_000_000)
    ap.add_argument("--check", action="store_true", help="fail if Dc/Validation.lean is stale")
    args = ap.parse_args()

    progs = [p for _, p in PROGRAMS]
    lean = difftest.run_lean(progs, 70, args.dc_olean)
    elf = elf_difftest.run_elf_shard(progs, args.vsa_olean, 20_000_000)
    lines = [
        "import Dc.Adequacy",
        "",
        "/-!",
        "# Validation: outputs of the RISC-V dc binary, derived in the semantics",
        "",
        "Generated by `scripts/dc/gen_validation.py`; do not edit. Each program's",
        "output was produced by `dc-port/dc-riscv-htif.elf` on the Sail RV64 model",
        "(`Vsa.runElf`, exit code 0) and by host GNU dc; the theorem states that",
        "`dc -e PROGRAM` has exactly that output in the semantics `Dc.Runs`",
        "(line length 70), checked by the kernel.",
        "-/",
        "",
        "namespace Dc.Validation",
        "",
    ]
    for (name, prog), want, (code, steps, got) in zip(PROGRAMS, lean, elf):
        host = difftest.run_dc(prog, 70, 10.0)
        if want is None or code != 0 or got != want or host != want:
            print(f"disagreement on {name}: lean {want!r} elf {code} {got!r} host {host!r}")
            return 1
        pb = [ord(c) for c in prog]
        ob = list(want)
        doc = prog.replace("-/", "- /")
        text = want.decode("latin-1").replace("-/", "- /")
        lines += [
            f"/-- `{doc}` prints",
            "```",
            text.rstrip("\n"),
            "```",
            f"(RISC-V: {steps} machine steps). -/",
            f"theorem {name}_valid :",
            f"    Runs 70 {pb}",
            f"      {ob} ∧",
            f"    ∀ o, Runs 70 {pb} o →",
            f"      o = {ob} :=",
            f"  runOut_spec (fuel := {args.fuel}) (by decide)",
            "",
        ]
    lines += ["end Dc.Validation", ""]
    text = "\n".join(lines)
    if args.check:
        if OUT.read_text() != text:
            print("Dc/Validation.lean is stale")
            return 1
        return 0
    OUT.write_text(text)
    print(f"wrote {OUT} ({len(PROGRAMS)} theorems)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
